---
# tasks file for sssd configure
#
- name: /etc/sssd/sssd.conf
  ansible.builtin.template:
    dest: /etc/sssd/sssd.conf
    group: root
    mode: 0600
    owner: root
    src: sssd.conf.j2
  notify:
    - restart sssd
    - enable services

- name: cert files
  ansible.builtin.copy:
    content: "{{ sssd_tls_cacert }}"
    dest: "{{ sssd_tls_cacert_path | default('/etc/ssl/certs/cacert.crt') }}"
    mode: 0644
  notify:
    - restart sssd
  when:
    - sssd_tls_cacert
