---
# tasks file for sssd
#
- name: load os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml
  tags: [ vars ]

- name: install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - install-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
    - install-{{ ansible_distribution }}.yml
    - install-{{ ansible_os_family }}.yml
    - install.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml
